//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSerco.SQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientFlag
    {
        public int idFlag { get; set; }
        public int IdCliente { get; set; }
        public int IdUser { get; set; }
        public string CodP { get; set; }
        public int Status { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
