//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSerco.SQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gestion
    {
        public int IdGestion { get; set; }
        public int IdCliente { get; set; }
        public string CodPrestamo { get; set; }
        public string NameDeudor { get; set; }
        public Nullable<int> IdDpto { get; set; }
        public Nullable<int> IdMncpo { get; set; }
        public string Urbanizacion { get; set; }
        public string Direccion { get; set; }
        public Nullable<System.DateTime> FechaGestion { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdTipo { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        public virtual Municipios Municipios { get; set; }
        public virtual TipoAcuerdo TipoAcuerdo { get; set; }
    }
}
