//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSerco.SQL.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int IdUser { get; set; }
        public int IdRol { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<System.DateTime> FLastUpdate { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual RolesUsuario RolesUsuario { get; set; }
    }
}
